version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern_frontend
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend
    restart: always
    networks:
      - mindbotics-network

  # Node.js Express Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern_backend
    env_file:
      - ./server/.env
    expose:
      - "5000"
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
    restart: always
    networks:
      - mindbotics-network

networks:
  mindbotics-network:
    name: mindbotics-network
