services:
  nginx-proxy:
    image: nginx:alpine
    container_name: global_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../MindBotics/nginx/certs:/etc/nginx/certs/mindbotics:ro
    networks:
      - mlm-network
      - mindbotics-network
      - bm2-network

networks:
  mlm-network:
    external: true
  mindbotics-network:
    external: true
  bm2-network:
    external: true
